import 'package:lucide_icons_flutter/lucide_icons.dart';
import '../models/tool_item.dart';
import '../theme/app_colors.dart';

class AppTools {
  // ── 1. Featured Tools ───────────────────────────────────────────
  static const List<ToolItem> featuredTools = [
    ToolItem(
      id: 'pdf-editor',
      label: 'PDF Editor',
      description: 'In-place text editing & object replacement',
      route: '/tools/pdf-editor',
      icon: LucideIcons.fileSignature,
      color: AppColors.toolPurple,
      softColor: AppColors.toolPurpleSoft,
      category: ToolCategory.pdf,
      isPro: true,
    ),
    ToolItem(
      id: 'merge-pdf',
      label: 'Merge PDF',
      description: 'Combine multiple PDFs into one',
      route: '/tools/merge',
      icon: LucideIcons.files,
      color: AppColors.toolBlue,
      softColor: AppColors.toolBlueSoft,
      category: ToolCategory.pdf,
    ),
    ToolItem(
      id: 'split-pdf',
      label: 'Split PDF',
      description: 'Split by ranges, every N or single pages',
      route: '/tools/split',
      icon: LucideIcons.scissors,
      color: AppColors.toolRed,
      softColor: AppColors.toolRedSoft,
      category: ToolCategory.pdf,
    ),
    ToolItem(
      id: 'compress-pdf',
      label: 'Compress PDF',
      description: 'Reduce file size with multi-level optimization',
      route: '/tools/compress',
      icon: LucideIcons.minimize2,
      color: AppColors.toolOrange,
      softColor: AppColors.toolOrangeSoft,
      category: ToolCategory.pdf,
    ),
    ToolItem(
      id: 'summarize-pdf',
      label: 'AI Summary',
      description: 'Detailed, short, key points & action items',
      route: '/ai/summarize',
      icon: LucideIcons.sparkles,
      color: AppColors.toolPurple,
      softColor: AppColors.toolPurpleSoft,
      category: ToolCategory.ai,
      isAi: true,
    ),
    ToolItem(
      id: 'ask-pdf',
      label: 'AI Document Chat',
      description: 'Interactive conversational Q&A and research',
      route: '/ai/ask',
      icon: LucideIcons.messageSquare,
      color: AppColors.toolBlue,
      softColor: AppColors.toolBlueSoft,
      category: ToolCategory.ai,
      isAi: true,
    ),
    ToolItem(
      id: 'protect-pdf',
      label: 'Protect PDF',
      description: '256-bit AES password encryption & permissions',
      route: '/security/protect',
      icon: LucideIcons.lock,
      color: AppColors.toolRed,
      softColor: AppColors.toolRedSoft,
      category: ToolCategory.security,
    ),
    ToolItem(
      id: 'smart-redaction',
      label: 'Redact Data',
      description: 'AI privacy scan & permanent blackouts',
      route: '/security/redact',
      icon: LucideIcons.eyeOff,
      color: AppColors.toolOrange,
      softColor: AppColors.toolOrangeSoft,
      category: ToolCategory.security,
    ),
  ];

  // ── 2. AI Document Intelligence Suite ───────────────────────────
  static const List<ToolItem> aiTools = [
    ToolItem(
      id: 'ai-ocr',
      label: 'OCR Text & Layout',
      description: 'Extract text & tables from scans/images',
      route: '/ai/ocr',
      icon: LucideIcons.scanLine,
      color: AppColors.toolBlue,
      softColor: AppColors.toolBlueSoft,
      category: ToolCategory.ai,
      isAi: true,
    ),
    ToolItem(
      id: 'summarize-pdf',
      label: 'AI Summary',
      description: 'Detailed, short, key points & action items',
      route: '/ai/summarize',
      icon: LucideIcons.sparkles,
      color: AppColors.toolPurple,
      softColor: AppColors.toolPurpleSoft,
      category: ToolCategory.ai,
      isAi: true,
    ),
    ToolItem(
      id: 'semantic-compare',
      label: 'Semantic Compare',
      description: 'Compare meaning & temporal/financial changes',
      route: '/ai/compare',
      icon: LucideIcons.gitCompare,
      color: AppColors.toolPurple,
      softColor: AppColors.toolPurpleSoft,
      category: ToolCategory.ai,
      isAi: true,
    ),
    ToolItem(
      id: 'similarity-matrix',
      label: 'Similarity Score',
      description: 'Pairwise similarity & duplicate detection',
      route: '/ai/similarity',
      icon: LucideIcons.layoutGrid,
      color: AppColors.toolIndigo,
      softColor: AppColors.toolIndigoSoft,
      category: ToolCategory.ai,
      isAi: true,
    ),
    ToolItem(
      id: 'ask-pdf',
      label: 'AI Document Chat',
      description: 'Interactive conversational Q&A and research',
      route: '/ai/ask',
      icon: LucideIcons.messageSquare,
      color: AppColors.toolBlue,
      softColor: AppColors.toolBlueSoft,
      category: ToolCategory.ai,
      isAi: true,
    ),
    ToolItem(
      id: 'semantic-search',
      label: 'Semantic Search',
      description: 'Search document by intent and meaning',
      route: '/ai/search',
      icon: LucideIcons.search,
      color: AppColors.toolTeal,
      softColor: AppColors.toolTealSoft,
      category: ToolCategory.ai,
      isAi: true,
    ),
    ToolItem(
      id: 'classify-pdf',
      label: 'Document Classify',
      description: 'Auto-identify paper, resume, invoice, contract',
      route: '/ai/classify',
      icon: LucideIcons.tag,
      color: AppColors.toolOrange,
      softColor: AppColors.toolOrangeSoft,
      category: ToolCategory.ai,
      isAi: true,
    ),
    ToolItem(
      id: 'extract-info',
      label: 'Information Extract',
      description: 'Structured fields from invoices, CVs & papers',
      route: '/ai/extract-info',
      icon: LucideIcons.fileSearch,
      color: AppColors.toolPink,
      softColor: AppColors.toolPinkSoft,
      category: ToolCategory.ai,
      isAi: true,
    ),
    ToolItem(
      id: 'translate-pdf',
      label: 'AI Translation',
      description: 'Translate into 15+ languages',
      route: '/ai/translate',
      icon: LucideIcons.languages,
      color: AppColors.toolGreen,
      softColor: AppColors.toolGreenSoft,
      category: ToolCategory.ai,
      isAi: true,
    ),
    ToolItem(
      id: 'writing-assistant',
      label: 'Writing Assistant',
      description: 'Grammar, paraphrase, formal & tone polish',
      route: '/ai/writing-assist',
      icon: LucideIcons.penTool,
      color: AppColors.toolGreen,
      softColor: AppColors.toolGreenSoft,
      category: ToolCategory.ai,
      isAi: true,
    ),
    ToolItem(
      id: 'quality-checker',
      label: 'Quality Checker',
      description: 'Audit structure, citations & readability',
      route: '/ai/quality-checker',
      icon: LucideIcons.checkCheck,
      color: AppColors.toolTeal,
      softColor: AppColors.toolTealSoft,
      category: ToolCategory.ai,
      isAi: true,
    ),
  ];

  // ── 3. PDF Processing & Pages ───────────────────────────────────
  static const List<ToolItem> pdfTools = [
    ToolItem(
      id: 'merge-pdf',
      label: 'Merge PDF',
      description: 'Combine multiple PDFs into one',
      route: '/tools/merge',
      icon: LucideIcons.files,
      color: AppColors.toolBlue,
      softColor: AppColors.toolBlueSoft,
      category: ToolCategory.pdf,
    ),
    ToolItem(
      id: 'split-pdf',
      label: 'Split PDF',
      description: 'Split by ranges, every N or single pages',
      route: '/tools/split',
      icon: LucideIcons.scissors,
      color: AppColors.toolRed,
      softColor: AppColors.toolRedSoft,
      category: ToolCategory.pdf,
    ),
    ToolItem(
      id: 'compress-pdf',
      label: 'Compress PDF',
      description: 'Reduce file size with multi-level optimization',
      route: '/tools/compress',
      icon: LucideIcons.minimize2,
      color: AppColors.toolOrange,
      softColor: AppColors.toolOrangeSoft,
      category: ToolCategory.pdf,
    ),
    ToolItem(
      id: 'extract-pages',
      label: 'Extract Pages',
      description: 'Extract specific pages into new PDF',
      route: '/tools/extract-pages',
      icon: LucideIcons.fileOutput,
      color: AppColors.toolTeal,
      softColor: AppColors.toolTealSoft,
      category: ToolCategory.pdf,
    ),
    ToolItem(
      id: 'rotate-pdf',
      label: 'Rotate PDF',
      description: 'Rotate page orientation permanently',
      route: '/tools/rotate',
      icon: LucideIcons.rotateCw,
      color: AppColors.toolBlue,
      softColor: AppColors.toolBlueSoft,
      category: ToolCategory.pdf,
    ),
    ToolItem(
      id: 'watermark',
      label: 'Watermark',
      description: 'Add text or logo watermarks',
      route: '/tools/watermark',
      icon: LucideIcons.stamp,
      color: AppColors.toolTeal,
      softColor: AppColors.toolTealSoft,
      category: ToolCategory.pdf,
    ),
    ToolItem(
      id: 'organize-pages',
      label: 'Organize Pages',
      description: 'Reorder, delete, duplicate & rotate',
      route: '/tools/organize-pages',
      icon: LucideIcons.layers,
      color: AppColors.toolIndigo,
      softColor: AppColors.toolIndigoSoft,
      category: ToolCategory.pdf,
    ),
    ToolItem(
      id: 'pdf-editor',
      label: 'PDF Editor',
      description: 'In-place text editing & object replacement',
      route: '/tools/pdf-editor',
      icon: LucideIcons.fileSignature,
      color: AppColors.toolPurple,
      softColor: AppColors.toolPurpleSoft,
      category: ToolCategory.pdf,
      isPro: true,
    ),
  ];

  // ── 4. Security & Privacy Suite ─────────────────────────────────
  static const List<ToolItem> securityTools = [
    ToolItem(
      id: 'protect-pdf',
      label: 'Protect PDF',
      description: '256-bit AES password encryption & permissions',
      route: '/security/protect',
      icon: LucideIcons.lock,
      color: AppColors.toolRed,
      softColor: AppColors.toolRedSoft,
      category: ToolCategory.security,
    ),
    ToolItem(
      id: 'smart-redaction',
      label: 'Redact Data',
      description: 'AI privacy scan & permanent blackouts',
      route: '/security/redact',
      icon: LucideIcons.eyeOff,
      color: AppColors.toolOrange,
      softColor: AppColors.toolOrangeSoft,
      category: ToolCategory.security,
    ),
    ToolItem(
      id: 'digital-sign',
      label: 'Digital Sign',
      description: 'Draw, type, or stamp digital signatures',
      route: '/security/sign',
      icon: LucideIcons.fileSignature,
      color: AppColors.toolIndigo,
      softColor: AppColors.toolIndigoSoft,
      category: ToolCategory.security,
    ),
    ToolItem(
      id: 'metadata-manager',
      label: 'Metadata Manager',
      description: 'Inspect, edit, or sanitize metadata for privacy',
      route: '/security/metadata',
      icon: LucideIcons.info,
      color: AppColors.toolBlue,
      softColor: AppColors.toolBlueSoft,
      category: ToolCategory.security,
    ),
  ];

  // ── 5. Document Conversions Studio ──────────────────────────────
  static const List<ToolItem> conversionTools = [
    ToolItem(
      id: 'word-to-pdf',
      label: 'Word to PDF',
      description: 'Convert DOC/DOCX documents to PDF format',
      route: '/tools/convert?from=word&to=pdf',
      icon: LucideIcons.fileText,
      color: AppColors.toolBlue,
      softColor: AppColors.toolBlueSoft,
      category: ToolCategory.convert,
    ),
    ToolItem(
      id: 'pdf-to-word',
      label: 'PDF to Word',
      description: 'Convert PDF documents to editable DOCX',
      route: '/tools/convert?from=pdf&to=word',
      icon: LucideIcons.fileOutput,
      color: AppColors.toolIndigo,
      softColor: AppColors.toolIndigoSoft,
      category: ToolCategory.convert,
    ),
    ToolItem(
      id: 'excel-to-pdf',
      label: 'Excel to PDF',
      description: 'Convert XLS/XLSX spreadsheets to PDF',
      route: '/tools/convert?from=excel&to=pdf',
      icon: LucideIcons.table,
      color: AppColors.toolGreen,
      softColor: AppColors.toolGreenSoft,
      category: ToolCategory.convert,
    ),
    ToolItem(
      id: 'pdf-to-excel',
      label: 'PDF to Excel',
      description: 'Extract tables and data to XLSX format',
      route: '/tools/convert?from=pdf&to=excel',
      icon: LucideIcons.fileSpreadsheet,
      color: AppColors.toolTeal,
      softColor: AppColors.toolTealSoft,
      category: ToolCategory.convert,
    ),
    ToolItem(
      id: 'ppt-to-pdf',
      label: 'PPT to PDF',
      description: 'Convert PowerPoint slides to PDF',
      route: '/tools/convert?from=ppt&to=pdf',
      icon: LucideIcons.presentation,
      color: AppColors.toolOrange,
      softColor: AppColors.toolOrangeSoft,
      category: ToolCategory.convert,
    ),
    ToolItem(
      id: 'pdf-to-ppt',
      label: 'PDF to PPT',
      description: 'Convert PDF pages into PowerPoint slides',
      route: '/tools/convert?from=pdf&to=ppt',
      icon: LucideIcons.fileSliders,
      color: AppColors.toolPink,
      softColor: AppColors.toolPinkSoft,
      category: ToolCategory.convert,
    ),
    ToolItem(
      id: 'image-to-pdf',
      label: 'Image to PDF',
      description: 'Convert JPG, PNG, WEBP images to PDF',
      route: '/tools/convert?from=image&to=pdf',
      icon: LucideIcons.image,
      color: AppColors.toolPurple,
      softColor: AppColors.toolPurpleSoft,
      category: ToolCategory.convert,
    ),
    ToolItem(
      id: 'pdf-to-image',
      label: 'PDF to Image',
      description: 'Render PDF pages as high-resolution images',
      route: '/tools/convert?from=pdf&to=image',
      icon: LucideIcons.images,
      color: AppColors.toolBlue,
      softColor: AppColors.toolBlueSoft,
      category: ToolCategory.convert,
    ),
  ];

  // ── 6. Image Format Converter ───────────────────────────────────
  static const List<ToolItem> imageFormatTools = [
    ToolItem(
      id: 'jpg-to-png',
      label: 'JPG to PNG',
      description: 'Convert JPG to PNG',
      route: '/tools/image-converter?to=png',
      icon: LucideIcons.image,
      color: AppColors.toolBlue,
      softColor: AppColors.toolBlueSoft,
      category: ToolCategory.image,
    ),
    ToolItem(
      id: 'png-to-jpg',
      label: 'PNG to JPG',
      description: 'Convert PNG to JPG',
      route: '/tools/image-converter?to=jpg',
      icon: LucideIcons.image,
      color: AppColors.toolGreen,
      softColor: AppColors.toolGreenSoft,
      category: ToolCategory.image,
    ),
    ToolItem(
      id: 'webp-to-jpg',
      label: 'WebP to JPG/PNG',
      description: 'Convert WebP to JPG or PNG',
      route: '/tools/image-converter?to=png',
      icon: LucideIcons.imagePlus,
      color: AppColors.toolPurple,
      softColor: AppColors.toolPurpleSoft,
      category: ToolCategory.image,
    ),
    ToolItem(
      id: 'heic-to-jpg',
      label: 'HEIC to JPG',
      description: 'Convert Apple HEIC to JPG',
      route: '/tools/image-converter?to=jpg',
      icon: LucideIcons.camera,
      color: AppColors.toolOrange,
      softColor: AppColors.toolOrangeSoft,
      category: ToolCategory.image,
    ),
    ToolItem(
      id: 'bmp-to-jpg',
      label: 'BMP to JPG/PNG',
      description: 'Convert BMP to JPG or PNG',
      route: '/tools/image-converter?to=png',
      icon: LucideIcons.fileImage,
      color: AppColors.toolTeal,
      softColor: AppColors.toolTealSoft,
      category: ToolCategory.image,
    ),
    ToolItem(
      id: 'image-manipulator',
      label: 'Image Adjust & Manipulator',
      description: 'Adjust brightness, contrast, saturation & filters',
      route: '/tools/image-manipulator',
      icon: LucideIcons.sliders,
      color: AppColors.toolPink,
      softColor: AppColors.toolPinkSoft,
      category: ToolCategory.image,
    ),
  ];

  // ── 7. Image Compressor ⭐ ──────────────────────────────────────
  static const List<ToolItem> imageCompressorTools = [
    ToolItem(
      id: 'image-comp-low',
      label: 'Low Compression',
      description: 'High quality, larger file size',
      route: '/tools/image-compressor?preset=low',
      icon: LucideIcons.fileArchive,
      color: AppColors.toolGreen,
      softColor: AppColors.toolGreenSoft,
      category: ToolCategory.image,
    ),
    ToolItem(
      id: 'image-comp-med',
      label: 'Medium Compression',
      description: 'Balanced quality & size',
      route: '/tools/image-compressor?preset=medium',
      icon: LucideIcons.minimize2,
      color: AppColors.toolOrange,
      softColor: AppColors.toolOrangeSoft,
      category: ToolCategory.image,
    ),
    ToolItem(
      id: 'image-comp-high',
      label: 'High Compression',
      description: 'Smaller file size, lower quality',
      route: '/tools/image-compressor?preset=high',
      icon: LucideIcons.minimize,
      color: AppColors.toolRed,
      softColor: AppColors.toolRedSoft,
      category: ToolCategory.image,
    ),
    ToolItem(
      id: 'image-comp-custom',
      label: 'Custom Compression',
      description: 'User selects compression level',
      route: '/tools/image-compressor?preset=custom',
      icon: LucideIcons.slidersHorizontal,
      color: AppColors.toolPurple,
      softColor: AppColors.toolPurpleSoft,
      category: ToolCategory.image,
    ),
  ];

  // ── 8. Media Downloader (YouTube & Spotify) ──────────────────────
  static const List<ToolItem> mediaDownloaderTools = [
    ToolItem(
      id: 'youtube-downloader',
      label: 'YouTube Video',
      description: 'Download HD videos and audio directly from YouTube links',
      route: '/tools/media-downloader?type=youtube',
      icon: LucideIcons.video,
      color: AppColors.toolRed,
      softColor: AppColors.toolRedSoft,
      category: ToolCategory.media,
    ),
    ToolItem(
      id: 'spotify-downloader',
      label: 'Spotify Audio',
      description: 'Download high-bitrate MP3 tracks from Spotify URLs',
      route: '/tools/media-downloader?type=spotify',
      icon: LucideIcons.music,
      color: AppColors.toolGreen,
      softColor: AppColors.toolGreenSoft,
      category: ToolCategory.media,
    ),
  ];

  // ── 9. Video Format Converter ───────────────────────────────────
  static const List<ToolItem> videoConverterTools = [
    ToolItem(
      id: 'video-to-mp4',
      label: 'Convert to MP4',
      description: 'Convert to MP4 format',
      route: '/tools/video-converter?to=mp4',
      icon: LucideIcons.video,
      color: AppColors.toolBlue,
      softColor: AppColors.toolBlueSoft,
      category: ToolCategory.video,
    ),
    ToolItem(
      id: 'video-to-webm',
      label: 'Convert to WebM',
      description: 'Convert to WebM format',
      route: '/tools/video-converter?to=webm',
      icon: LucideIcons.film,
      color: AppColors.toolGreen,
      softColor: AppColors.toolGreenSoft,
      category: ToolCategory.video,
    ),
    ToolItem(
      id: 'video-to-mov',
      label: 'Convert to MOV',
      description: 'Convert to MOV format',
      route: '/tools/video-converter?to=mov',
      icon: LucideIcons.clapperboard,
      color: AppColors.toolIndigo,
      softColor: AppColors.toolIndigoSoft,
      category: ToolCategory.video,
    ),
    ToolItem(
      id: 'video-to-gif',
      label: 'Convert to GIF',
      description: 'Convert to animated GIF',
      route: '/tools/video-converter?to=gif',
      icon: LucideIcons.sparkles,
      color: AppColors.toolPink,
      softColor: AppColors.toolPinkSoft,
      category: ToolCategory.video,
    ),
  ];

  // ── 10. Video Compressor ────────────────────────────────────────
  static const List<ToolItem> videoCompressorTools = [
    ToolItem(
      id: 'video-comp-low',
      label: 'Low Compression',
      description: 'High quality, large size',
      route: '/tools/video-compressor?preset=low',
      icon: LucideIcons.video,
      color: AppColors.toolGreen,
      softColor: AppColors.toolGreenSoft,
      category: ToolCategory.video,
    ),
    ToolItem(
      id: 'video-comp-med',
      label: 'Medium Compression',
      description: 'Balanced quality & size',
      route: '/tools/video-compressor?preset=medium',
      icon: LucideIcons.minimize2,
      color: AppColors.toolOrange,
      softColor: AppColors.toolOrangeSoft,
      category: ToolCategory.video,
    ),
    ToolItem(
      id: 'video-comp-high',
      label: 'High Compression',
      description: 'Small file size',
      route: '/tools/video-compressor?preset=high',
      icon: LucideIcons.minimize,
      color: AppColors.toolRed,
      softColor: AppColors.toolRedSoft,
      category: ToolCategory.video,
    ),
  ];

  // ── 11. Archive & Compression (.ZIP, .RAR, .TAR, .GZ, .7Z, .BZ2) ─
  static const List<ToolItem> archiveTools = [
    ToolItem(
      id: 'archive-extract',
      label: 'Extract & View Archive',
      description: 'Extract .ZIP, .RAR, .TAR, .GZ, .7Z & .BZ2 files',
      route: '/tools/archive?mode=extract',
      icon: LucideIcons.folderInput,
      color: AppColors.toolOrange,
      softColor: AppColors.toolOrangeSoft,
      category: ToolCategory.archive,
    ),
    ToolItem(
      id: 'archive-create-zip',
      label: 'Create ZIP Archive',
      description: 'Compress and package multiple files to .ZIP',
      route: '/tools/archive?mode=create_zip',
      icon: LucideIcons.archive,
      color: AppColors.toolGreen,
      softColor: AppColors.toolGreenSoft,
      category: ToolCategory.archive,
    ),
    ToolItem(
      id: 'archive-create-tar',
      label: 'Create TAR / GZ',
      description: 'Pack folders into .TAR & .TAR.GZ archives',
      route: '/tools/archive?mode=create_tar',
      icon: LucideIcons.packagePlus,
      color: AppColors.toolTeal,
      softColor: AppColors.toolTealSoft,
      category: ToolCategory.archive,
    ),
    ToolItem(
      id: 'archive-convert',
      label: 'Convert Archive',
      description: 'Convert RAR, 7Z, TAR & BZ2 to universal ZIP',
      route: '/tools/archive?mode=convert',
      icon: LucideIcons.refreshCw,
      color: AppColors.toolIndigo,
      softColor: AppColors.toolIndigoSoft,
      category: ToolCategory.archive,
    ),
    ToolItem(
      id: 'archive-studio',
      label: 'Archive Studio',
      description: 'Complete multi-format archive manager suite',
      route: '/tools/archive',
      icon: LucideIcons.archiveRestore,
      color: AppColors.toolPurple,
      softColor: AppColors.toolPurpleSoft,
      category: ToolCategory.archive,
    ),
  ];

  // ── 12. Audio Format Converter ──────────────────────────────────
  static const List<ToolItem> audioConverterTools = [
    ToolItem(
      id: 'audio-to-mp3',
      label: 'Convert to MP3',
      description: 'Convert to MP3 audio format with high fidelity',
      route: '/tools/audio-converter?to=mp3',
      icon: LucideIcons.music,
      color: AppColors.toolGreen,
      softColor: AppColors.toolGreenSoft,
      category: ToolCategory.audio,
    ),
    ToolItem(
      id: 'audio-to-wav',
      label: 'Convert to WAV',
      description: 'Convert to uncompressed studio WAV format',
      route: '/tools/audio-converter?to=wav',
      icon: LucideIcons.audioLines,
      color: AppColors.toolBlue,
      softColor: AppColors.toolBlueSoft,
      category: ToolCategory.audio,
    ),
    ToolItem(
      id: 'audio-to-ogg',
      label: 'Convert to OGG',
      description: 'Convert to open-source OGG Vorbis audio',
      route: '/tools/audio-converter?to=ogg',
      icon: LucideIcons.disc,
      color: AppColors.toolOrange,
      softColor: AppColors.toolOrangeSoft,
      category: ToolCategory.audio,
    ),
  ];

  // Quick Tools for Home Screen (Featured)
  static List<ToolItem> get quickTools => featuredTools;

  // Aggregate List of all tools
  static List<ToolItem> get allTools => [
    ...featuredTools,
    ...aiTools,
    ...pdfTools,
    ...securityTools,
    ...conversionTools,
    ...imageFormatTools,
    ...imageCompressorTools,
    ...mediaDownloaderTools,
    ...videoConverterTools,
    ...videoCompressorTools,
    ...archiveTools,
    ...audioConverterTools,
  ];

  static ToolItem? getById(String id) {
    try {
      return allTools.firstWhere((tool) => tool.id == id);
    } catch (_) {
      return null;
    }
  }

  static ToolItem? getByRoute(String route) {
    try {
      return allTools.firstWhere((tool) => tool.route == route);
    } catch (_) {
      return null;
    }
  }
}
