import 'dart:io';
import 'dart:ui';
import 'package:path_provider/path_provider.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';
import '../../core/models/mind_map_model.dart';
import '../../core/services/pdf_engine.dart';

class DiagramService {
  // Generate NotebookLM-style Mind Map Hierarchy from Document Structure
  Future<List<MindMapNode>> generateMindMapFromDocument(File file) async {
    String text = '';
    try {
      text = await PdfEngine.extractTextFromPdf(file);
    } catch (_) {}

    final lines = text.split(RegExp(r'\r?\n')).where((l) => l.trim().isNotEmpty).toList();
    final docTitle = file.uri.pathSegments.last.replaceAll('.pdf', '').replaceAll('_', ' ');

    final rootId = 'root_node';
    final rootNode = MindMapNode(
      id: rootId,
      title: docTitle.isEmpty ? 'Document Analysis' : docTitle,
      x: 0,
      y: 0,
      colorHex: 0xFF6366F1,
    );

    final List<MindMapNode> flatList = [rootNode];
    int headingCount = 0;

    for (final line in lines) {
      final trimmed = line.trim();
      if (trimmed.length < 65 &&
          (trimmed.toUpperCase() == trimmed ||
              RegExp(r'^\d+[\.\)]|\b(Chapter|Section|Part|Introduction|Conclusion|Method|Results|Overview|Analysis|Summary)\b',
                      caseSensitive: false)
                  .hasMatch(trimmed))) {
        headingCount++;
        final childId = 'node_$headingCount';
        final isEven = headingCount % 2 == 0;
        final childNode = MindMapNode(
          id: childId,
          title: trimmed,
          parentId: rootId,
          x: isEven ? 220.0 : -220.0,
          y: (headingCount * 65.0) - 120.0,
          colorHex: isEven ? 0xFF06B6D4 : 0xFF10B981,
        );

        // Add 2 AI concept sub-nodes for each section (NotebookLM style)
        final sub1 = MindMapNode(
          id: '${childId}_sub1',
          title: 'Key Insights & Data',
          parentId: childId,
          x: isEven ? 400.0 : -400.0,
          y: (headingCount * 65.0) - 140.0,
          colorHex: 0xFF8B5CF6,
        );
        final sub2 = MindMapNode(
          id: '${childId}_sub2',
          title: 'Actionable Takeaways',
          parentId: childId,
          x: isEven ? 400.0 : -400.0,
          y: (headingCount * 65.0) - 100.0,
          colorHex: 0xFFEC4899,
        );

        childNode.children.addAll([sub1, sub2]);
        childNode.childrenIds.addAll([sub1.id, sub2.id]);
        rootNode.children.add(childNode);
        rootNode.childrenIds.add(childId);
        flatList.addAll([childNode, sub1, sub2]);

        if (headingCount >= 8) break;
      }
    }

    // Fallback if no clear headings were matched
    if (rootNode.children.isEmpty) {
      final defaultTopics = [
        {'title': 'Executive Overview', 'color': 0xFF06B6D4},
        {'title': 'Core Methodology', 'color': 0xFF10B981},
        {'title': 'Key Analytical Findings', 'color': 0xFFF59E0B},
        {'title': 'Strategic Recommendations', 'color': 0xFFEC4899},
      ];

      int idx = 0;
      for (final topic in defaultTopics) {
        idx++;
        final childId = 'default_node_$idx';
        final isEven = idx % 2 == 0;
        final child = MindMapNode(
          id: childId,
          title: topic['title'] as String,
          parentId: rootId,
          x: isEven ? 220.0 : -220.0,
          y: (idx * 75.0) - 150.0,
          colorHex: topic['color'] as int,
        );

        final sub1 = MindMapNode(
          id: '${childId}_sub1',
          title: 'Section Summary',
          parentId: childId,
          colorHex: 0xFF8B5CF6,
        );
        final sub2 = MindMapNode(
          id: '${childId}_sub2',
          title: 'Key References',
          parentId: childId,
          colorHex: 0xFF3B82F6,
        );

        child.children.addAll([sub1, sub2]);
        child.childrenIds.addAll([sub1.id, sub2.id]);
        rootNode.children.add(child);
        rootNode.childrenIds.add(childId);
        flatList.addAll([child, sub1, sub2]);
      }
    }

    return flatList;
  }

  // Generate Presentation Deck from Document Sections
  Future<PresentationDeck> generatePresentationFromDocument(File file) async {
    final text = await PdfEngine.extractTextFromPdf(file);
    final paragraphs = text.split(RegExp(r'\n\s*\n')).where((p) => p.trim().length > 20).toList();

    final List<SlideItem> slides = [];
    final docTitle = file.uri.pathSegments.last.replaceAll('.pdf', '');

    // Title Slide
    slides.add(
      SlideItem(
        slideTitle: docTitle,
        bulletPoints: ['Generated by MaskerV Presentation Studio', 'Document Intelligence Summary'],
        speakerNotes: 'Welcome to the presentation for $docTitle.',
      ),
    );

    for (int i = 0; i < paragraphs.length; i++) {
      final p = paragraphs[i].trim();
      final sentences = p.split(RegExp(r'\.|\n')).where((s) => s.trim().length > 5).toList();
      final slideTitle = sentences.isNotEmpty ? sentences.first.trim() : 'Section ${i + 1}';
      final bullets = sentences.skip(1).take(3).map((s) => s.trim()).toList();

      slides.add(
        SlideItem(
          slideTitle: slideTitle.length > 40 ? '${slideTitle.substring(0, 40)}...' : slideTitle,
          bulletPoints: bullets.isNotEmpty ? bullets : [p],
          speakerNotes: p,
        ),
      );
      if (slides.length >= 8) break;
    }

    return PresentationDeck(title: docTitle, slides: slides);
  }

  // Export Presentation Deck as PDF Slides
  Future<File> exportPresentationAsPdf(PresentationDeck deck, String outputFileName) async {
    final document = PdfDocument();

    final titleFont = PdfStandardFont(PdfFontFamily.helvetica, 20, style: PdfFontStyle.bold);
    final bulletFont = PdfStandardFont(PdfFontFamily.helvetica, 14);

    for (final slide in deck.slides) {
      final page = document.pages.add();
      // Draw Slide Title
      page.graphics.drawString(
        slide.slideTitle,
        titleFont,
        bounds: const Rect.fromLTWH(20, 30, 460, 40),
        brush: PdfSolidBrush(PdfColor(33, 150, 243)),
      );

      double y = 90;
      for (final bullet in slide.bulletPoints) {
        page.graphics.drawString(
          '• $bullet',
          bulletFont,
          bounds: Rect.fromLTWH(40, y, 440, 30),
          brush: PdfSolidBrush(PdfColor(33, 33, 33)),
        );
        y += 35;
      }
    }

    final outputDir = await getApplicationDocumentsDirectory();
    final outputFile = File('${outputDir.path}/$outputFileName.pdf');
    await outputFile.writeAsBytes(document.saveSync());
    document.dispose();
    return outputFile;
  }
}
