import 'dart:io';
import 'dart:ui';
import 'package:path_provider/path_provider.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';
import '../../core/models/mind_map_model.dart';
import '../../core/services/pdf_engine.dart';

class DiagramService {
  // Generate Mind Map Hierarchy from Document Structure
  Future<List<MindMapNode>> generateMindMapFromDocument(File file) async {
    final text = await PdfEngine.extractTextFromPdf(file);
    final lines = text.split(RegExp(r'\r?\n')).where((l) => l.trim().isNotEmpty).toList();

    final List<MindMapNode> nodes = [];
    final rootId = 'root_node';
    final docTitle = file.uri.pathSegments.last.replaceAll('.pdf', '');

    nodes.add(
      MindMapNode(
        id: rootId,
        title: docTitle,
        x: 0,
        y: 0,
        colorHex: 0xFF2196F3,
      ),
    );

    int headingCount = 0;
    double currentAngle = 0;

    for (final line in lines) {
      final trimmed = line.trim();
      // Identify main headings
      if (trimmed.length < 50 && (trimmed.toUpperCase() == trimmed || RegExp(r'^\d+\.|\b(Chapter|Section|Introduction|Conclusion|Method|Results)\b', caseSensitive: false).hasMatch(trimmed))) {
        headingCount++;
        final childId = 'node_$headingCount';
        final angle = currentAngle;
        currentAngle += 0.8;

        nodes.add(
          MindMapNode(
            id: childId,
            title: trimmed,
            parentId: rootId,
            x: 180 * (angle == 0 ? 1 : (headingCount % 2 == 0 ? 1 : -1)),
            y: 70.0 * headingCount - 150,
            colorHex: 0xFF4CAF50,
          ),
        );
        nodes.first.childrenIds.add(childId);
        if (nodes.length >= 10) break;
      }
    }

    return nodes;
  }

  // Generate Presentation Deck from Document Sections
  Future<PresentationDeck> generatePresentationFromDocument(File file) async {
    final text = await PdfEngine.extractTextFromPdf(file);
    final paragraphs = text.split(RegExp(r'\n\s*\n')).where((p) => p.trim().length > 20).toList();

    final List<SlideItem> slides = [];
    final docTitle = file.uri.pathSegments.last.replaceAll('.pdf', '');

    // Title Slide
    slides.add(
      SlideItem(
        slideTitle: docTitle,
        bulletPoints: ['Generated by PaperKit Presentation Studio', 'Document Intelligence Summary'],
        speakerNotes: 'Welcome to the presentation for $docTitle.',
      ),
    );

    for (int i = 0; i < paragraphs.length; i++) {
      final p = paragraphs[i].trim();
      final sentences = p.split(RegExp(r'\.|\n')).where((s) => s.trim().length > 5).toList();
      final slideTitle = sentences.isNotEmpty ? sentences.first.trim() : 'Section ${i + 1}';
      final bullets = sentences.skip(1).take(3).map((s) => s.trim()).toList();

      slides.add(
        SlideItem(
          slideTitle: slideTitle.length > 40 ? '${slideTitle.substring(0, 40)}...' : slideTitle,
          bulletPoints: bullets.isNotEmpty ? bullets : [p],
          speakerNotes: p,
        ),
      );
      if (slides.length >= 8) break;
    }

    return PresentationDeck(title: docTitle, slides: slides);
  }

  // Export Presentation Deck as PDF Slides
  Future<File> exportPresentationAsPdf(PresentationDeck deck, String outputFileName) async {
    final document = PdfDocument();

    final titleFont = PdfStandardFont(PdfFontFamily.helvetica, 20, style: PdfFontStyle.bold);
    final bulletFont = PdfStandardFont(PdfFontFamily.helvetica, 14);

    for (final slide in deck.slides) {
      final page = document.pages.add();
      // Draw Slide Title
      page.graphics.drawString(
        slide.slideTitle,
        titleFont,
        bounds: const Rect.fromLTWH(20, 30, 460, 40),
        brush: PdfSolidBrush(PdfColor(33, 150, 243)),
      );

      double y = 90;
      for (final bullet in slide.bulletPoints) {
        page.graphics.drawString(
          '• $bullet',
          bulletFont,
          bounds: Rect.fromLTWH(40, y, 440, 30),
          brush: PdfSolidBrush(PdfColor(33, 33, 33)),
        );
        y += 35;
      }
    }

    final outputDir = await getApplicationDocumentsDirectory();
    final outputFile = File('${outputDir.path}/$outputFileName.pdf');
    await outputFile.writeAsBytes(document.saveSync());
    document.dispose();
    return outputFile;
  }
}
