import 'dart:io';
import 'dart:typed_data';

import 'package:pointycastle/export.dart';

import 'vault_key_service.dart';

/// Handles AES-256-GCM authenticated encryption and decryption for vault files.
///
/// Encrypted file format:
///   [12 bytes: nonce/IV][remaining bytes: ciphertext + 16-byte GCM auth tag]
///
/// SECURITY PROPERTIES:
/// - Confidentiality: AES-256-GCM
/// - Integrity/Authentication: built-in GCM auth tag (16 bytes)
/// - Unique nonce per file: generated by [VaultKeyService.generateNonce]
/// - No hardcoded key — key sourced from [VaultKeyService]
/// - No logging of key material or plaintext
class VaultEncryptionService {
  static const int _nonceLength = 12; // 96-bit GCM nonce
  static const int _tagLength = 16;   // 128-bit GCM auth tag

  final VaultKeyService _keyService;

  VaultEncryptionService({VaultKeyService? keyService})
      : _keyService = keyService ?? VaultKeyService();

  /// Encrypts [sourceFile] and writes the result to [destFile].
  ///
  /// Returns the written destination file on success.
  /// Throws [VaultEncryptionException] on any failure.
  Future<File> encryptFile(File sourceFile, File destFile) async {
    try {
      final key = await _keyService.getOrCreateMasterKey();
      final nonce = VaultKeyService.generateNonce();
      final plaintext = await sourceFile.readAsBytes();

      final ciphertext = _aesgcmEncrypt(key, nonce, plaintext);

      // Write: [nonce (12 bytes)][ciphertext + auth tag]
      final output = BytesBuilder()
        ..add(nonce)
        ..add(ciphertext);

      await destFile.writeAsBytes(output.toBytes(), flush: true);
      return destFile;
    } on VaultKeyException {
      rethrow;
    } catch (e) {
      throw VaultEncryptionException('Encryption failed: ${e.runtimeType}');
    }
  }

  /// Decrypts [encryptedFile] and returns the plaintext bytes in memory.
  ///
  /// The plaintext is NEVER written to disk by this method — the caller
  /// is responsible for secure temporary handling.
  /// Throws [VaultEncryptionException] on failure (including auth tag mismatch).
  Future<Uint8List> decryptFile(File encryptedFile) async {
    try {
      final key = await _keyService.getOrCreateMasterKey();
      final rawData = await encryptedFile.readAsBytes();

      if (rawData.length < _nonceLength + _tagLength) {
        throw VaultEncryptionException('Encrypted file is too small or corrupted');
      }

      final nonce = Uint8List.sublistView(rawData, 0, _nonceLength);
      final ciphertextWithTag = Uint8List.sublistView(rawData, _nonceLength);

      return _aesgcmDecrypt(key, nonce, ciphertextWithTag);
    } on VaultKeyException {
      rethrow;
    } on VaultEncryptionException {
      rethrow;
    } catch (e) {
      throw VaultEncryptionException('Decryption failed: ${e.runtimeType}');
    }
  }

  // ────────────────────────────────────────────────────────────────
  // Private AES-GCM helpers using PointyCastle
  // ────────────────────────────────────────────────────────────────

  Uint8List _aesgcmEncrypt(Uint8List key, Uint8List nonce, Uint8List plaintext) {
    final cipher = GCMBlockCipher(AESEngine());
    final params = AEADParameters(
      KeyParameter(key),
      _tagLength * 8, // tag length in bits
      nonce,
      Uint8List(0), // empty additional authenticated data
    );
    cipher.init(true, params); // true = encrypt

    final outputLength = cipher.getOutputSize(plaintext.length);
    final output = Uint8List(outputLength);
    var offset = cipher.processBytes(plaintext, 0, plaintext.length, output, 0);
    offset += cipher.doFinal(output, offset);
    return output.sublist(0, offset);
  }

  Uint8List _aesgcmDecrypt(Uint8List key, Uint8List nonce, Uint8List ciphertextWithTag) {
    final cipher = GCMBlockCipher(AESEngine());
    final params = AEADParameters(
      KeyParameter(key),
      _tagLength * 8,
      nonce,
      Uint8List(0),
    );
    cipher.init(false, params); // false = decrypt

    final outputLength = cipher.getOutputSize(ciphertextWithTag.length);
    final output = Uint8List(outputLength);
    var offset = cipher.processBytes(
      ciphertextWithTag, 0, ciphertextWithTag.length, output, 0,
    );
    try {
      offset += cipher.doFinal(output, offset);
    } catch (_) {
      throw VaultEncryptionException(
        'Authentication tag mismatch — file may be corrupted or tampered',
      );
    }
    return output.sublist(0, offset);
  }
}

class VaultEncryptionException implements Exception {
  final String message;
  const VaultEncryptionException(this.message);

  @override
  String toString() => 'VaultEncryptionException: $message';
}
